Сверстана страница с запросами
TitTolkachev/tsu-schedule pull request #10
Opened 2023-03-09 06:18 UTC by XxtEri

2023-03-09 08:50 UTC, GreenpixDev requested changes
1. request.component.ts и search-request.pipe.ts надо было делать в папке pages/admin/requests по аналогии с другими страницами в админ-панели. А то что у нас везде по разному.
2. В принципе, можно было бы просто скопировать прошлые админ страницы и поменять всё под запросы, но уже ладно

2023-03-09 08:50 UTC, GreenpixDev commented on src/app/pages/admin/requests/requests-page/requests-page.component.ts
> +    {name: "Иноземцева Татьяна Андреевна", email: "sd@mail.com", group: undefined},
Надо было сделать дата-класс по аналогии с другими страницами админ-панели (см. пример в ветке [develop](https://github.com/TitTolkachev/tsu-schedule/blob/develop/src/app/models/audience.ts))
```typescript
export class RegistrationRequest {

  readonly name: string
  readonly email: string
  readonly group: string

  constructor(name: string, email: string, group: string) {
    this.name = name
    this.email = email
    this.group = group
  }
}
```

2023-03-09 08:50 UTC, GreenpixDev commented on src/app/pages/admin/requests/requests-page/requests-page.component.html
> +</div>
Не хватает модальных окон для отклонения и приёма запросов.

2023-03-09 09:47 UTC, XxtEri commented on src/app/pages/admin/requests/requests-page/requests-page.component.ts
> +    {name: "Иноземцева Татьяна Андреевна", email: "sd@mail.com", group: undefined},
Я думала, что этим ты занимаешься (

2023-03-09 12:57 UTC, GreenpixDev requested changes
1. Ты видимо случайно search-request вынесла именно request-element, а не в pages/admin/requests
2. У тебя при нажатии на крестик открывается окно подтверждения

2023-03-10 15:50 UTC, GreenpixDev approved these changes
Я бы ещё добавил окно подтверждения на кнопку "Принять все"

2023-03-10 15:50 UTC, merged